pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'prod',
                    url: 'https://github.com/nik089/Event-Management-System.git'
            }
        }
        

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t angular-app .'
            }
        }

        stage('Run Docker Container') {
            steps {
                bat '''
                docker rm -f angular-container || exit 0
                docker run -d -p 80:80 --name angular-container angular-app
                '''
            }
        }
    }
}
