pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                dir('EMS') {
                    bat '''
                    docker build -t angular-app .
                    '''
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                bat '''
                docker stop angular-container 2>nul
                docker rm angular-container 2>nul
                docker run -d -p 80:80 --name angular-container angular-app
                '''
            }
        }
    }
}
